export const LinkList = [
  {
    id: "link-1",
    title: "GitHub",
    color: "#1A1A1A",
    icon: "./images/icon-github.svg",
  },
  {
    id: "link-2",
    title: "Frontend Mentor",
    color: "#FFF",
    icon: "./images/icon-frontend-mentor.svg",
  },
  {
    id: "link-3",
    title: "Twitter",
    color: "#43B7E9",
    icon: "./images/icon-twitter.svg",
  },
  {
    id: "link-4",
    title: "LinkedIn",
    color: "#2D68FF",
    icon: "./images/icon-linkedin.svg",
  },
  {
    id: "link-5",
    title: "YouTube",
    color: "#EE3939",
    icon: "./images/icon-youtube.svg",
  },
  {
    id: "link-6",
    title: "Facebook",
    color: "#2442AC",
    icon: "./images/icon-facebook.svg",
  },
  {
    id: "link-7",
    title: "Twitch",
    color: "#EE3FC8",
    icon: "./images/icon-twitch.svg",
  },
  {
    id: "link-8",
    title: "Dev.to",
    color: "#333",
    icon: "./images/icon-devto.svg",
  },
  {
    id: "link-9",
    title: "Codewars",
    color: "#8A1A50",
    icon: "./images/icon-codewars.svg",
  },
  {
    id: "link-10",
    title: "freeCodeCamp",
    color: "#302267",
    icon: "./images/icon-freecodecamp.svg",
  },
  {
    id: "link-11",
    title: "GitLab",
    color: "#EB4925",
    icon: "./images/icon-gitlab.svg",
  },
  {
    id: "link-12",
    title: "Hashnode",
    color: "#0330D1",
    icon: "./images/icon-hashnode.svg",
  },
  {
    id: "link-13",
    title: "Stack Overflow",
    color: "#EC7100",
    icon: "./images/icon-stack-overflow.svg",
  },
];
